class Kitchen extends ContentItem
	@registerItem 'kitchen', 1, 'Buttermilk Fried Chicken', 'buttermilkfriedchicken'
	@registerItem 'kitchen', 2, 'Pulled Pork', 'pulledpork'
	@registerItem 'kitchen', 3, 'Biscuits and Gravy', 'biscuitsandgravy'
	@registerItem 'kitchen', 4, 'Chicken and Sausage Jambalaya', 'chickenandsausagejambalaya'
	@registerItem 'kitchen', 5, 'Country Fried Steak', 'countryfriedsteak'
	@registerItem 'kitchen', 5, 'Sweet Potato Casserole', 'sweetpotato'
	@registerItem 'kitchen', 6, 'Collard Greens', 'collardgreens'
	@registerItem 'kitchen', 7, 'Mac & Cheese', 'macandcheese'
	@registerItem 'kitchen', 8, 'Corn Casserole', 'corncasserole'
	@registerItem 'kitchen', 9, 'Bread Pudding', 'breadpudding'
	@registerItem 'kitchen', 10, 'Strawberry Pretzel Salad', 'strawberrypretzelsalad'
	@registerItem 'kitchen', 11, 'Pineapple Pretzel Salad', 'pineapplepretzelsalad'
	@registerItem 'kitchen', 12, 'Prosciutto with Melon', 'prosciuttowithmelon'
	@registerItem 'kitchen', 13, 'Prosciutto Wrapped Greens', 'prosciuttowrappedgreens'
