class Talks extends ContentItem
	@registerItem 'talks', 1, 'Time Is Trying To Kill You', 'timeistryingtokillyou'
	@registerItem 'talks', 2, 'Robot Royal Rumble', 'robotroyalrumble'
	@registerItem 'talks', 3, 'React Native To The Rescue', 'reactnativetotherescue'
	@registerItem 'talks', 4, 'React Native In The Wild', 'reactnativeinthewild'
	@registerItem 'talks', 5, 'React Native: Cross Platform Mobile At Ludicrous Speed', 'reactnativecrossplatformmobileatludicrousspeed'
	@registerItem 'talks', 6, 'I Can Read Your Mind With Javascript', 'icanreadyourmindwithjavascript'
	@registerItem 'talks', 7, 'Objective-C Can Do What?!?!?', 'objectiveccandowhat'
	@registerItem 'talks', 8, 'Watch Out For Swarming Node Bots', 'watchoutforswarmingnodebots'
	@registerItem 'talks', 9, 'Walk Up Gaming With Chromecast', 'walkupgamingwithchromecast'
	@registerItem 'talks', 10, 'Marvelous Mobile Ruby Development', 'marvelousmobilerubydevelopment'
	@registerItem 'talks', 11, 'Terminator', 'terminator'
	@registerItem 'talks', 12, 'Watch This', 'watchthis'
	@registerItem 'talks', 13, 'Robots Who Love Ruby', 'robotswholoveruby'
