class Talks extends ContentItem
	@registerItem 'talks', 1, 'Time Is Trying To Kill You', 'timeistryingtokillyou'
	@registerItem 'talks', 2, 'Objective-C Can Do What?!?!?', 'objectiveccandowhat'
	@registerItem 'talks', 3, 'Watch Out For Swarming Node Bots', 'watchoutforswarmingnodebots'
	@registerItem 'talks', 4, 'Walk Up Gaming With Chromecast', 'walkupgamingwithchromecast'
	@registerItem 'talks', 5, 'Marvelous Mobile Ruby Development', 'marvelousmobilerubydevelopment'
	@registerItem 'talks', 6, 'Terminator', 'terminator'
	@registerItem 'talks', 7, 'Watch This', 'watchthis'
	@registerItem 'talks', 8, 'Robots Who Love Ruby', 'robotswholoveruby'
	@registerItem 'talks', 9, 'Robot Royal Rumble', 'robotroyalrumble'